feat: add database models for user information, files and tasks
toadharvard/desbordante-server pull request #16
Opened 2023-11-27 21:18 UTC by raf-nr

Add pydantic models for tasks config and result
Add database models for tasks, files and user information

2023-12-12 18:18 UTC, toadharvard requested changes
Намного лучше, чем раньше, но делать еще оченб много.

2023-12-12 18:18 UTC, toadharvard commented on .env.example
> +POSTGRES_USER_TEST=admin
не дублируй, лучше подмени в тестах настройки

2023-12-12 18:18 UTC, toadharvard commented on .github/workflows/run-linter-and-tests.yaml
> +      - name: Set up docker
Эта генерация от чат-гпт совсем не подходит по контексту.

2023-12-12 18:18 UTC, toadharvard commented on .github/workflows/run-linter-and-tests.yaml
> +        uses: docker/login-action@v1
ты не пушишь ничего же, зачем?

2023-12-12 18:18 UTC, toadharvard commented on .github/workflows/run-linter-and-tests.yaml
> +      - name: Up all containers
Тут зависает, так как не демона запускаешь

2023-12-12 18:18 UTC, toadharvard commented on .pre-commit-config.yaml
> +        exclude: tests/
Добавь опцию отключащую конкретную мешающую проверку, а не линтер на всех тестах.

2023-12-12 18:18 UTC, toadharvard commented on app/db/__init__.py
> +tables = {
Поддержка такого словаря та еще боль, лучше избавиться от него и убрать вообще все импорты. 
Лучше будет, если будут напрямую импортироваться нужные модели, а не через table

2023-12-12 18:18 UTC, toadharvard commented on app/db/__init__.py
> +from app.db.models.user_data_models.code import Code
Кажется избыточно так называть модули модели.
user_models -> user

2023-12-12 18:18 UTC, toadharvard commented on app/db/__init__.py
> +from app.db.models.file_data_models.column_stats import ColumnStats
Кажется это не имеет отношения к файлу. Это вроде бы задача, роль которой посчитать простые статистики.

2023-12-12 18:18 UTC, toadharvard commented on app/db/__init__.py
> -Base = declarative_base()
Мог бы тут и оставить. Читается заметно лучше.

2023-12-12 18:18 UTC, toadharvard commented on app/db/migrations/versions/50a96e7d78a4_.py
> +"""empty message
Миграция без нормального имени. Грустно читать, а понимать последовательность миграций еще сложнеее.

2023-12-12 18:18 UTC, toadharvard commented on app/db/migrations/versions/7556ff23ad16_.py
> +"""empty message
Тоже нужно имя

2023-12-12 18:18 UTC, toadharvard commented on app/db/models/file_data_models/column_stats.py
> +class ColumnStats(Base):
Слишком много None. Переспроси, вдруг это можно оптимизировать

2023-12-12 18:18 UTC, toadharvard commented on app/db/models/file_data_models/file_format.py
> +    id: Mapped[UUID] = mapped_column(
Страннл, вроде и PK, а вроде и FK

2023-12-12 18:18 UTC, toadharvard commented on app/db/models/file_data_models/file_format.py
> +    # For "SINGULAR"
Что это значит вообще. Переименуй переменные, чтобы не пришлось писать коменты

2023-12-12 18:18 UTC, toadharvard commented on app/db/models/user_data_models/code.py
> +    EMAIL_VERIFICATION = auto()
EMAIL_VERIFICATION_REQUIRED?

2023-12-12 18:18 UTC, toadharvard commented on app/db/models/user_data_models/permission.py
> +    USE_BUILTIN_DATASETS = auto()
`CAN` бла бла бла, это же возможность, а не действия

2023-12-12 18:18 UTC, toadharvard commented on app/tasks/models/task.py
> +    config: Mapped[str] = mapped_column(JSON)
Должен быть json у типа, ну или дикт

2023-12-12 18:18 UTC, toadharvard commented on app/tasks/models/task.py
> +class TaskStatusType(StrEnum):
TaskStatus вроде лучше?

2023-12-12 18:18 UTC, toadharvard commented on app/tasks/models/task.py
> +    result: Mapped[str] = mapped_column(JSON)
Тоже

2023-12-12 18:18 UTC, toadharvard commented on app/tasks/schema/ar/config.py
> +    min_support_ar: float
Нужны ограничения на все значения для всех Конфигураций, которые наследуются от GeneralTaskConfig. Используй возможности Pydantic для валидации

2023-12-12 18:18 UTC, toadharvard commented on app/tasks/schema/ar/result.py
> +    value_dictionary: str | None
Слишком странное название. Дикт, но типа стринг, так еще и Nonable

2023-12-12 18:18 UTC, toadharvard commented on app/tasks/schema/base_task_result.py
> +class BaseTaskResult(BaseModel):
Два термина для наиболее общего типа. Выбери Base и не исползуй General

2023-12-12 18:18 UTC, toadharvard commented on app/tasks/schema/cfd/result.py
> +    value_dictionary: str | None
Тоже самое назыание. Ничего совершенно не говорит.

2023-12-12 18:18 UTC, toadharvard commented on app/tasks/schema/cfd/result.py
> +    pk_column_indices: str | None
Это то ли индексы, то ли хрен знает что. Надо нормально типов добавить, которые бы помогли читать это без страданий.

2023-12-12 18:18 UTC, toadharvard commented on app/tasks/schema/mfd/config.py
> +    parametr: float
что такое параметр я понятия не имею и никто не понимает. заменить на нормальноее название, спросив антона

2023-12-12 18:18 UTC, toadharvard commented on app/tasks/schema/mfd/config.py
> +    lhs_indices: str
Тоже индексы, но почему-то стр

2023-12-12 18:18 UTC, toadharvard commented on app/tasks/schema/mfd/config.py
> +    q: int
И что это?

2023-12-12 18:18 UTC, toadharvard commented on app/tasks/schema/mfd/result.py
> +    result: bool | None
Это верификатор? Может быть is_holding или типа того, спроси у Антона

2023-12-12 18:18 UTC, toadharvard commented on app/tasks/schema/specific_typo_cluster/result.py
> +class SpecificTypoClusterTaskResult(BaseTaskResult):
Стреееемно, может ввести еще какую-то схему пайдентик, чтобы избавиться от миллиона отрицаний

2023-12-12 18:18 UTC, toadharvard commented on app/tasks/schema/stats/result.py
> +class StatsTaskResult(BaseTaskResult):
Точно в классе ничего не должно храниться? Странно, как будто бы та фигня, которую я просил вынести из информации о файле должна тут лежать. Ну или нет. Я не уверен, обсуди с Антоном

2023-12-12 18:18 UTC, toadharvard commented on app/tasks/schema/typo_cluster/config.py
> +    typo_fd: str
Почему это строка

2023-12-12 18:18 UTC, toadharvard commented on app/tasks/schema/typo_fd/config.py
> +    metric: MetricType
type_of_metric?

2023-12-12 18:18 UTC, toadharvard commented on dev-docker-compose.yaml
> +  postgres-test:
Не нужно 2 инстанса постгреса

2023-12-12 18:18 UTC, toadharvard commented on tests/conftest.py
> +def clean_tables(request, session_test):
можно очищать в 10 раз проще

2023-12-12 18:18 UTC, toadharvard commented on tests/conftest.py
> +    Base.metadata.drop_all(test_engine)
есть подозрение, что если дропнуть таблицы все, то это то же самое, что и clean tables

2023-12-12 18:18 UTC, toadharvard commented on tests/conftest.py
> +def session_test():
название

2023-12-12 18:18 UTC, toadharvard commented on tests/conftest.py
> +tables = [
кринж

2023-12-12 18:18 UTC, toadharvard commented on tests/conftest.py
> +    Session = sessionmaker(test_engine, expire_on_commit=False)
Точно с большой?

2023-12-12 18:18 UTC, toadharvard commented on tests/db_tests/test_database_queries.py
> +def test_database_queries(
огромный тест, название ничего не говорит о том, что ты тут тетсируешь

2023-12-12 18:18 UTC, toadharvard commented on tests/fixtures/fetch_data_from_db.py
> +            with session.connection():
90% я уверен это не нужно.

2023-12-12 18:18 UTC, toadharvard commented on tests/fixtures/fetch_data_from_db.py
> +def fetch_all_data_from_table(session_test):
Я хз зачем эти файлы, слишком странные.  Я бы предпочел просто получать текущую уде подготовленнуб сессию в тест в виде фикстуры. Посмотри social network prototype

2023-12-12 18:18 UTC, toadharvard commented on tests/fixtures/insert_data_in_db.py
> +import pytest
Ну опять стремно очень

2023-12-12 18:18 UTC, toadharvard commented on tests/fixtures/insert_data_in_db.py
> +import pytest
Зачем эти функции  в функции. Что это тебе дает кроме головной боли....

2023-12-12 18:18 UTC, toadharvard commented on tests/fixtures/insert_data_in_db.py
> +def insert_device_data(session_test):
Прикинь таблица поменяется, вот смеху будет это править

2023-12-12 18:18 UTC, toadharvard commented on tests/fixtures/insert_data_in_db.py
> +    return add_task
ад и израиль

2023-12-12 18:18 UTC, toadharvard commented on tests/fixtures/insert_data_in_db.py
> +import pytest
Все что ты делаешь это данные вставляешь. Это решается типа, ээээ в 2 строчки?

2023-12-12 18:18 UTC, toadharvard commented on tests/tests_data/code.py
> +from datetime import datetime
Я бы предпочел испоьзование билблиотеки fake

2023-12-12 18:18 UTC, toadharvard commented on tests/tests_data/code.py
> +from datetime import datetime
Они умеет генерить по схеме тестовые данные

2023-12-12 18:18 UTC, toadharvard commented on tests/tests_data/file_info.py
> +        "path": "2///",
бредятина. Реально просто напиши нрмальные типа в схеме и генерь себе тестовые данные валидные...

2023-12-12 18:18 UTC, toadharvard commented on tests/conftest.py
> +        yield
че ты елдишь?

2023-12-12 18:18 UTC, toadharvard commented on tests/fixtures/fetch_data_from_db.py
> +                data = session.query(tables[model_name]).first()
select вместо query используют

2023-12-16 11:26 UTC, raf-nr commented on app/db/__init__.py
> +tables = {
✓

2023-12-16 11:30 UTC, raf-nr commented on app/db/__init__.py
> +from app.db.models.user_data_models.code import Code
✓

2023-12-16 11:30 UTC, raf-nr commented on app/db/__init__.py
> -Base = declarative_base()
✓

2023-12-16 11:34 UTC, raf-nr commented on app/db/models/file_data_models/file_format.py
> +    # For "SINGULAR"
✓

2023-12-16 11:41 UTC, raf-nr commented on app/db/models/user_data_models/code.py
> +    EMAIL_VERIFICATION = auto()
✓

2023-12-16 11:43 UTC, raf-nr commented on app/db/models/user_data_models/permission.py
> +    USE_BUILTIN_DATASETS = auto()
✓

2023-12-16 14:43 UTC, raf-nr commented on app/tasks/models/task.py
> +class TaskStatusType(StrEnum):
✓

2023-12-16 14:47 UTC, raf-nr commented on app/tasks/schema/typo_fd/config.py
> +    metric: MetricType
✓

2023-12-16 14:48 UTC, raf-nr commented on tests/conftest.py
> +    Session = sessionmaker(test_engine, expire_on_commit=False)
Точно

2023-12-16 17:29 UTC, raf-nr commented on tests/conftest.py
> +        yield
мы с помощью этого не перезапускаем наши фикстуры(у которых scope=function) между тестами одного параметризованного теста

2023-12-16 17:50 UTC, raf-nr commented on tests/fixtures/fetch_data_from_db.py
> +                data = session.query(tables[model_name]).first()
✓

2023-12-21 22:28 UTC, raf-nr commented on app/db/models/file_data_models/column_stats.py
> +class ColumnStats(Base):
Решили вопрос

2023-12-21 22:28 UTC, raf-nr commented on app/db/models/file_data_models/file_format.py
> +    id: Mapped[UUID] = mapped_column(
Изменено

2023-12-21 22:39 UTC, raf-nr commented on app/tasks/models/task.py
> +    config: Mapped[str] = mapped_column(JSON)
готово

2023-12-21 22:39 UTC, raf-nr commented on app/tasks/models/task.py
> +    result: Mapped[str] = mapped_column(JSON)
✓

2023-12-21 22:40 UTC, raf-nr commented on app/tasks/schema/ar/config.py
> +    min_support_ar: float
✓

2023-12-21 22:44 UTC, raf-nr commented on app/tasks/schema/base_task_result.py
> +class BaseTaskResult(BaseModel):
сделал

2023-12-21 22:44 UTC, raf-nr commented on app/tasks/schema/cfd/result.py
> +    pk_column_indices: str | None
заменил на список интов

2023-12-21 22:44 UTC, raf-nr commented on app/tasks/schema/mfd/config.py
> +    parametr: float
исправил

2023-12-21 22:47 UTC, raf-nr commented on app/tasks/schema/mfd/config.py
> +    lhs_indices: str
больше не стр!

2023-12-21 22:48 UTC, raf-nr commented on app/tasks/schema/mfd/config.py
> +    q: int
ку-грам-ленхт
исправил

2023-12-21 22:48 UTC, raf-nr commented on app/tasks/schema/stats/result.py
> +class StatsTaskResult(BaseTaskResult):
ты как всегда прав!
исправил

2023-12-21 22:55 UTC, raf-nr commented on dev-docker-compose.yaml
> +  postgres-test:
как скажешь

2023-12-21 23:04 UTC, raf-nr commented on app/tasks/schema/ar/result.py
> +    value_dictionary: str | None
решили делать диктант

2023-12-21 23:04 UTC, raf-nr commented on app/tasks/schema/cfd/result.py
> +    value_dictionary: str | None
исправил тип на дикт

2023-12-21 23:06 UTC, raf-nr commented on app/tasks/schema/typo_cluster/config.py
> +    typo_fd: str
в ноде: "TypoFD это зависимость, которую мы хотим проверить 
Она состоит из индексов атрибутов 
Слева может быть от 0 до скольки угодно атрибутов, справа один атрибут 
Скорее всего хранится просто в виде строки, где индексы разделены запятыми 
И последний индекс соответствует правой части"

решили описать пайдентик схемой всё, исправлено

2023-12-21 23:07 UTC, raf-nr commented on app/db/__init__.py
> +from app.db.models.file_data_models.column_stats import ColumnStats
ага

2023-12-21 23:17 UTC, raf-nr commented on .github/workflows/run-linter-and-tests.yaml
> +      - name: Up all containers
😈 😈 😈 😈 😈 😈

2023-12-21 23:17 UTC, raf-nr commented on .github/workflows/run-linter-and-tests.yaml
> +        uses: docker/login-action@v1
действительно зачем

2023-12-21 23:18 UTC, raf-nr commented on .github/workflows/run-linter-and-tests.yaml
> +      - name: Set up docker
я конечно не чат-гпт, но согласен

2023-12-21 23:20 UTC, raf-nr commented on .env.example
> +POSTGRES_USER_TEST=admin
готово

2023-12-21 23:43 UTC, raf-nr commented on app/db/migrations/versions/50a96e7d78a4_.py
> +"""empty message
добавил имя

2023-12-21 23:44 UTC, raf-nr commented on app/db/migrations/versions/7556ff23ad16_.py
> +"""empty message
добавил имя и описание

2023-12-21 23:45 UTC, raf-nr commented on app/tasks/schema/mfd/result.py
> +    result: bool | None
исправил

2023-12-21 23:50 UTC, raf-nr commented on app/tasks/schema/specific_typo_cluster/result.py
> +class SpecificTypoClusterTaskResult(BaseTaskResult):
ок

2023-12-21 23:51 UTC, raf-nr commented on tests/conftest.py
> +    Base.metadata.drop_all(test_engine)
это неправда.

2023-12-21 23:51 UTC, raf-nr commented on tests/conftest.py
> +def session_test():
исправил

2023-12-21 23:51 UTC, raf-nr commented on tests/fixtures/fetch_data_from_db.py
> +            with session.connection():
ты прав

2023-12-22 00:09 UTC, raf-nr commented on tests/conftest.py
> +def clean_tables(request, session_test):
ну чет не круто между всеми тестами дропать таблицу

2023-12-22 00:19 UTC, raf-nr commented on tests/conftest.py
> +tables = [
убрал

2023-12-22 01:20 UTC, raf-nr commented on tests/fixtures/insert_data_in_db.py
> +def insert_device_data(session_test):
удалено это

2023-12-22 01:20 UTC, raf-nr commented on tests/fixtures/insert_data_in_db.py
> +import pytest
удалил

2023-12-22 01:20 UTC, raf-nr commented on tests/fixtures/fetch_data_from_db.py
> +def fetch_all_data_from_table(session_test):
удалил

2023-12-22 01:20 UTC, raf-nr commented on tests/db_tests/test_database_queries.py
> +def test_database_queries(
подправил

2023-12-22 01:20 UTC, raf-nr commented on tests/fixtures/insert_data_in_db.py
> +    return add_task
удалил

2023-12-22 01:21 UTC, raf-nr commented on tests/tests_data/file_info.py
> +        "path": "2///",
поправил

2023-12-22 12:41 UTC, toadharvard requested changes

2023-12-22 12:41 UTC, toadharvard commented on .pre-commit-config.yaml
> +        files: ^env\.py$
Кажется ты полностью убил линтер, просто добавь правило в исключение в pyproject.toml

2023-12-22 12:41 UTC, toadharvard commented on .github/workflows/run-linter-and-tests.yaml
> +        run: make up -d &
Подумать как убрать необходимость в &

2023-12-22 12:41 UTC, toadharvard commented on app/db/migrations/versions/08c0492d6748_.py
> +"""
Файлы миграций назваются нечитаемо. В спецификации alembic есть возмоность генерировать нормальные имена.

2023-12-22 12:41 UTC, toadharvard commented on app/tasks/schema/ar/config.py
> +    min_support_ar: Annotated[float, Field(ge=0, le=1, metadata={"decimal_places": 4})]
Поля metadata не существует у Field. Поправь везде, где встречается

2023-12-22 12:41 UTC, toadharvard commented on tests/db_tests/test_database_queries.py
> +def test_database_queries(
Все еще большой

2023-12-22 12:41 UTC, toadharvard commented on .github/workflows/run-linter-and-tests.yaml
> +        run: make up -d &
Возможно это ломает CI

2023-12-22 13:30 UTC, toadharvard approved these changes

2023-12-22 20:56 UTC, merged